name: 'datahub'
version: '0.1.0'
config-version: 2

require-dbt-version: [">=1.3.0", "<2.0.0"]

macro-paths: ["macros"]

target-path: "target"
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"

log-path: "logs"
